-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 28, 2020 at 05:51 AM
-- Server version: 10.4.6-MariaDB
-- PHP Version: 7.3.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `kalam_2020`
--

-- --------------------------------------------------------

--
-- Table structure for table `department_admin`
--

CREATE TABLE `department_admin` (
  `id` int(11) NOT NULL,
  `admin_id` varchar(20) NOT NULL,
  `email_id` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `department_admin`
--

INSERT INTO `department_admin` (`id`, `admin_id`, `email_id`, `password`) VALUES
(1, 'Admin_agri', 'ashanmugasundram@siet.ac.in', 'Admin_agri'),
(2, 'Admin_biotech', 'tchitradevi@siet.ac.in', 'Admin_biotech'),
(3, 'Admin_biomedical', 'pnancy@siet.ac.in', 'Admin_biomedical'),
(4, 'Admin_civil', 'janitha@siet.ac.in', 'Admin_civil'),
(5, 'Admin_cse', 'cse@siet.ac.in', 'Admin_cse'),
(6, 'Admin_ece', 'ranjith@siet.ac.in', 'Admin_ece'),
(7, 'Admin_eee', 'arivoliseee@siet.ac.in', 'Admin_eee'),
(8, 'Admin_mech', 'sudhagar.s@siet.ac.in', 'Admin_mech'),
(9, 'Admin_it', 'sandhiyab@siet.ac.in', 'Admin_it'),
(10, 'Admin_foodtech', 'kvasantharajft@siet.ac.in', 'Admin_foodtech'),
(11, 'Admin', 'admin@admin', 'Admin');

-- --------------------------------------------------------

--
-- Table structure for table `events_registration`
--

CREATE TABLE `events_registration` (
  `id` int(11) NOT NULL,
  `Kalam_id` varchar(100) NOT NULL,
  `event_id` varchar(100) NOT NULL,
  `email` varchar(50) NOT NULL,
  `full_name` varchar(20) NOT NULL,
  `college` varchar(100) NOT NULL,
  `mob_no` int(13) NOT NULL,
  `event_name` varchar(100) NOT NULL,
  `description` varchar(10000) NOT NULL,
  `event_rules` varchar(10000) NOT NULL,
  `event_date` varchar(100) NOT NULL,
  `event_start_time` varchar(100) NOT NULL,
  `event_end_time` varchar(100) NOT NULL,
  `venue` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `events_registration`
--

INSERT INTO `events_registration` (`id`, `Kalam_id`, `event_id`, `email`, `full_name`, `college`, `mob_no`, `event_name`, `description`, `event_rules`, `event_date`, `event_start_time`, `event_end_time`, `venue`) VALUES
(1, 'KALAM11590', 'E10003', 'jeevan@gmail.com', 'Jeevan', 'SRIPC', 987765654, 'PAPER PREZENTO', 'Think out loud!! under the following topics: \r\n1. Advanced Construction Practices\r\n2. Ground Improvement Techniques\r\n3. Automated Highway Systems\r\n4. GIS &amp;amp; Remote Sensing\r\n5. Sustainable Materials In Constructions\r\n6. water and waste water analysis\r\n7. Advance Pavement Design \r\n', 'Two members per team \r\n10 min for presentation and 3min for queries.', '07/02/2020', '9:30', '11:30pm', 'MELH 12'),
(2, 'KALAM52546', 'E10003', 'samcladson08@gmail.com', 'sam cladson', 'SIET', 2147483647, 'PAPER PREZENTO', 'Think out loud!! under the following topics: \r\n1. Advanced Construction Practices\r\n2. Ground Improvement Techniques\r\n3. Automated Highway Systems\r\n4. GIS &amp;amp; Remote Sensing\r\n5. Sustainable Materials In Constructions\r\n6. water and waste water analysis\r\n7. Advance Pavement Design \r\n', 'Two members per team \r\n10 min for presentation and 3min for queries.', '07/02/2020', '9:30', '11:30pm', 'MELH 12'),
(3, 'KALAM52546', 'E10013', 'samcladson08@gmail.com', 'sam cladson', 'SIET', 2147483647, 'COMPERING', '&amp;quot;Hello there! Do you run your tongue to spread positivity ? Are you looking for a stage to engage audience and keep them live in events ?\r\nHere comes an opportunity to excel your talent in compeering.&amp;quot;', '1.The registration for this event is on the spot\r\n2.The event will take place in 2 rounds -prelims and finals\r\n3.In the preliminary round the participants will be given 6 topics. The participants can choose a topic to speak.\r\n4.In the final round the the participants will be given the topic on the spot to speak.', '08/02/2020', '10.00 AM ', '3.00 PM', 'Seminar hall-1'),
(4, 'KALAM52546', 'E10023', 'samcladson08@gmail.com', 'sam cladson', 'SIET', 2147483647, 'CODE SWAPPING', 'A group of two programmers writes program for two problems simultaneously. The programmers want to swap among themselves based on the swap time.', '\r\n1. Each Team will be provided two Windows based system.\r\n2. Compiling or debugging the code using any kind of applications is not permitted.\r\n3. The codes would be written in C/C++/JAVA/PYTHON (Based on participant)\r\n4. Any malpractice would lead to straight disqualification.\r\n5. There will be  three rounds', '07/02/2020', '10.00 AM', '4.30 PM', 'lab - 06'),
(5, 'KALAM52546', 'E10024', 'samcladson08@gmail.com', 'sam cladson', 'SIET', 2147483647, 'Seminar', 'Biotechnology in 2030', 'Students should participate actively', '06/02/2020', '9.30 AM', '12.30.PM', 'Seminar Hall 1'),
(6, 'KALAM52546', 'E10025', 'samcladson08@gmail.com', 'sam cladson', 'SIET', 2147483647, 'Dock X', 'Molecular docking of protein-ligand using auto dock vina.\r\n\r\n', 'Requirement: Laptop is mandatory', '06/02/2020', '2.00 PM', '4.30 PM', 'LH 34 A');

-- --------------------------------------------------------

--
-- Table structure for table `event_details`
--

CREATE TABLE `event_details` (
  `id` int(11) NOT NULL,
  `admin_id` varchar(100) NOT NULL,
  `event_id` varchar(20) NOT NULL,
  `category` varchar(20) NOT NULL,
  `event_name` varchar(300) NOT NULL,
  `description` varchar(20000) NOT NULL,
  `event_rules` varchar(20000) NOT NULL,
  `student_coordinator_name` varchar(50) NOT NULL,
  `student_coordinator_number` varchar(20) NOT NULL,
  `staff_coordinator_name` varchar(1000) NOT NULL,
  `staff_coordinator_number` varchar(20) NOT NULL,
  `event_date` varchar(100) NOT NULL,
  `event_start_time` varchar(100) NOT NULL,
  `event_end_time` varchar(110) NOT NULL,
  `venue` varchar(100) NOT NULL,
  `status` int(11) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `event_details`
--

INSERT INTO `event_details` (`id`, `admin_id`, `event_id`, `category`, `event_name`, `description`, `event_rules`, `student_coordinator_name`, `student_coordinator_number`, `staff_coordinator_name`, `staff_coordinator_number`, `event_date`, `event_start_time`, `event_end_time`, `venue`, `status`) VALUES
(1, 'Admin_civil', 'E10001', 'Technical', 'DRAFTRIX', 'Imagination leads to visualization and conception. Draftrix aims at finding your inner talents of unique thinking and helps to plot thoughts using AUTOCAD software. The plot needs to be drawn based on problem statement laid before.', 'Duration:1hr \r\nMax Team Members: 2\r\n', 'Hari prasanth J', '9524492848', 'Muthukumar P AP/CIVIL', '9578490341', '06/02/2020', '1:30pm', '3:00pm', 'STAAD LAB (LAB NO.13)', 1),
(2, 'Admin_civil', 'E10002', 'Technical', 'GUEST LECTURE ON &quot;PRIMAVERA VS ENGINEERING CAREERS&quot;', 'Primavera and MS Project knowledge is more advantages to work at Project Planning and Controlling Systems and to get following positions in their industry which will be highly wanted openings in next years to CIVIL, MECHANICAL, ELECTRICAL and IT Engineers', 'college ID must be provided', 'BALAJI', '9159047589', 'Srividya R AP/CIVIL', '994488664', '06/02/2020', '9:30 am', '12:30pm', 'STAAD LAB (LAB NO.13)', 1),
(3, 'Admin_civil', 'E10003', 'Technical', 'PAPER PREZENTO', 'Think out loud!! under the following topics: \r\n1. Advanced Construction Practices\r\n2. Ground Improvement Techniques\r\n3. Automated Highway Systems\r\n4. GIS &amp; Remote Sensing\r\n5. Sustainable Materials In Constructions\r\n6. water and waste water analysis\r\n7. Advance Pavement Design \r\n', 'Two members per team \r\n10 min for presentation and 3min for queries.', 'Kaviko', '9095766534', 'Sreadethya V AP/CIVIL', '7402184530', '07/02/2020', '9:30', '11:30pm', 'MELH 12', 1),
(4, 'Admin_civil', 'E10004', 'Technical', 'SURVEY HUNT', 'Surveying being the cornerstone for any Civil Engineering  project.For each team task will be given, by which they have use their survey skills to finish the task.', 'Max team Members: 3', 'Sabari ', '9524295969', 'ANITHA J AP/CIVIL', '8870209437', '07/02/2020', '11:00 am', '12:30pm', 'SURVEY LAB-CIVIL DEPARTMENT', 1),
(5, 'Admin_civil', 'E10005', 'Technical', 'CUCRETE', 'can concrete actually float? Come prove it to us!!! In this event, participants are supposed to make a Concrete Structure which has floating property.\r\nUnleash your imagination and ideas to innovate the structure made, using CONCRETE', 'CRITERIA\r\n• You must design the mix and cast the concrete structures in size 20cmX10cmX10cm that can actually float in water within the specified restrictions.\r\n• Mix design grade:M20\r\n• The constituents of concrete (type and material) can be decided by the participants. Use of admixtures is allowed\r\n• Mix design report should be prepared as per is 456 &amp; is 10262.\r\n• Detailed report of the design mix should be submitted on the day of event.\r\n• Density, Floating capability, Strength, Appearance of the block will be evaluated.\r\n• High strength should be achieved with low density. \r\n• The cast block will be tested on FEB 07th 2020 to evaluate the 7th day compressive strength\r\n• Numbers of block to be casted: 3\r\n• The submitted design reports would be evaluated and the teams will be asked to give a brief oral presentation of their work upon which they will be questioned.\r\n• Points would be awarded according to the judging criteria and winners will be announced \r\nRULES: Team Member: 4 \r\n', 'Nandhakumar', '9698860907', 'SRI RUBAN AP/civil', '9791784565', '07/02/2020', '1:30pm', '3:00pm', 'concrete and highway lab', 1),
(6, 'Admin_cultural', 'E10006', 'Cultural', 'SOLO SINGING', 'Music gives a soul to the universe, wings to the mind, flight to the imagination and life to everything. Arohanam in the context of \r\nIndian classical music is the ascending scale of notes in a raga. It’s a platform to showcase your talents in music. Cheers guys!', '1. Maximum Time Duration is 6 minutes.\r\n2. Cine Songs or Album Songs can be presented.\r\n3. Karaoke has to be brought by the participants in pendrive. \r\n4. Judgement will be based on Quality of voice, Tempo, Pitching, Selection of song and General Impression.\r\n5. Any kind of vulgarity and profanity are strictly prohibited.\r\n6. Decision of the judges will be final. ', 'Dilip Saravanan. S', '7806804687', 'ROHIT', '7418095078', '08/02/2020', '09.30 AM', '02.00PM', 'Ball Room', 1),
(7, 'Admin_cultural', 'E10007', 'Cultural', 'BAND', '&quot;Battle with bands, if you dare&quot;. Come on guys, it’s time to battle with your clans-the bands, and let’s see who wins the battle with \r\nthe Eastern bands! Let the battle of bands begin!', '1.Maximum of 5 to 8 persons per team.\r\n2. No vulgar scenes should be performed.\r\n3. Online/ Onspot registration should be done.\r\n4. Judges decision will be final.\r\n5. Selection will be based upon the performance of the team and the weightage in their concept.\r\n6.Duration : 5 to 10 minutes.', 'Gautham Siddharth.S', '8608527396', 'ROHIT', '7418095078', '08/02/2020', '09.30 AM', '02.00PM', 'Ball Room', 1),
(8, 'Admin_cultural', 'E10008', 'Cultural', 'INSTRUMENTALS', 'Instrumental music is nonverbal and thus radically ambiguous. It doesn\'t lend itself to what might be called content-oriented \r\nanalysis, though plenty of intellectuals have tried to analyze it in precisely that way.', '1. This is a free style solo competition.\r\n2.  Maximum Time Duration is 5 minutes.\r\n3.  Instruments should be brought by the participants.\r\n4.  Participants are not allowed to use chord sheets or music notes or other sources.\r\n5.  Recorded performances will be disqualified.\r\n', ' Allan', '9003897274', 'ROHIT', '7418095078', '08/02/2020', '09.30 AM', '02.00PM', 'Ball Room', 1),
(9, 'Admin_cultural', 'E10009', 'Cultural', 'MONO ACT', 'Every scene you will ever act begins in the middle, and it is up to you, the actor, to provide what comes before..', '1.Duration:3-6 minutes\r\n2.Judges decision will be final\r\n3.Message must be conveyed perfectly.\r\n4.No vulgar music or acting should be done.\r\n5.Costume or any makeup requirements will not be provided.It should be brought by the participants itself&quot;', 'Deenadayalan.R ', '9791654694', 'Ram Nivash', '7339306046', '08/02/2020', '10.00 AM ', '3.00 PM', 'Seminar hall-2', 1),
(10, 'Admin_cultural', 'E10010', 'Cultural', 'STANDUP', 'Humour is the tendency of experiences to provoke laughter and provide amusement. People of all ages and culture respond\r\n to Humour. This event is to express how the participants are expert with humour and stage presence !', 'Registration can be done both digitally and on the spot.\r\nAll the participants must register.\r\nVulgarity/use of foul language may lead to disqualification and elimination of the team.\r\nTime limit for Prelims:3-4 minutes .\r\nFinals: 3-5 minute .\r\nCumulative marks will be taken for Results.\r\nDecision of Judges will be final and binding on all team.\r\n\r\nPRELIMS\r\nParticipants must prepare a concept of their own and perform within the time limit.\r\nFINALS\r\nA topic will be given to the finalists along with 15 mins from preparation\r\nThe best one among the finalists will be crowned as the thamasha raja/rani', 'Srinath B', '8838223841', 'Bharathkumar P', '8903212809', '08/02/2020', '10.00 AM ', '3.00 PM', 'Seminar hall-2', 1),
(11, 'Admin_cultural', 'E10011', 'Cultural', 'SKIT', 'Life is a walking shadow that struts and frets his hour upon the stage according to Shakespeare, but that is not the case when you \r\nhave a stage all to yourself and an applauding crowd to motivate you.', 'All the teams must register in prior.\r\nMaximum/Minimum  number of members per team is 6 to 12.\r\nThere are no restrictions with regard to scripts and original scripts, pre-written scripts and adaptations are all welcome.\r\nThe total time from stage entry to stage exit is 6-10 minutes.\r\nTeams using any props / Costume / Dressing must bring all their requirements and must be ready well in time as per instructions\r\n of the organizer.\r\nThe host college will provide no Props / costume /any material.\r\nDemonstrations using fire, water and breaking glass are not allowed on stage and participants will be held responsible for \r\nany damage to the stage.\r\nNo obscenities will be permitted on stage.', 'Srinath B', '8838223841', 'Ram Nivash', '7339306046', '08/02/2020', '10.00 AM ', '3.00 PM', 'Seminar hall-2', 1),
(12, 'Admin_cultural', 'E10012', 'Cultural', 'MIME', 'Mime is a form of silent art that involves acting or communicating using only movements, gestures and facial expressions. Mime is \r\n a theatrical medium, which is a performance art, involves acting out a story through body action and gestures to express the content \r\nor tell a story without using a speech or dialogues. Saying something without saying is not it so difficult, here is such an event,it is\r\n not that tough be there to witness it. The greatest audience awaits you at Kalam 2020!', '1.Maximum of 5 to 8 persons per team.\r\n2. No vulgar scenes should be performed.\r\n3. Online/ Onspot registration should be done.\r\n4. Judges decision will be final.\r\n5. Selection will be based upon the performance of the team and the weightage in their concept.\r\n6.Duration : 5 to 10 minutes.', 'Gowtham M.G', '8825432816', 'Ram Nivash', '7339306046', '08/02/2020', '10.00 AM ', '3.00 PM', 'Seminar hall-2', 1),
(13, 'Admin_cultural', 'E10013', 'Cultural', 'COMPERING', '&quot;Hello there! Do you run your tongue to spread positivity ? Are you looking for a stage to engage audience and keep them live in events ?\r\nHere comes an opportunity to excel your talent in compeering.&quot;', '1.The registration for this event is on the spot\r\n2.The event will take place in 2 rounds -prelims and finals\r\n3.In the preliminary round the participants will be given 6 topics. The participants can choose a topic to speak.\r\n4.In the final round the the participants will be given the topic on the spot to speak.', 'Srinivasini', '9080378726', 'G J SIDDHARTH', '7397176300', '08/02/2020', '10.00 AM ', '3.00 PM', 'Seminar hall-1', 1),
(14, 'Admin_cultural', 'E10014', 'Cultural', 'BEAT BOXING', 'Just because a sound is hard to do doesn’t mean it sounds good.Hello there! Do you run your tongue to spread positivity ? \r\nAre you looking for a stage to engage audience and keep them live in events ?Here comes an opportunity to excel your talent ', '1.The performance should not exceed 1 minute.\r\n2.The decision of the judges will be final.\r\n3.The performance which are performed within the given time will be highly considered.\r\n4.Online or onspot registration must be done.\r\n5.Selection is based on the accuracy of the music.', 'Blesson G ', '9043541643', 'Bharathkumar P', '8903212809', '08/02/2020', '10.00 AM ', '3.00 PM', 'Seminar hall-1', 1),
(15, 'Admin_cultural', 'E10015', 'Cultural', 'WHISTLE BOXING', 'The sound circulated like an autonomous being whose tentacles needed to experience a sensitive awareness of the terrain.', '1.Five selected songs will be given on  spot during the performance.\r\n2.The competitors must do a mashup of the given songs not exceeding 1 minute\r\n3.A minimum of 3 songs is to be performed and it is mandatory.\r\n4.Selection will be based on how best it\'s whistled.\r\n5.Bonus points are given if more than 3 songs whistled in a minute.\r\n6.The decision of the judges will be final.\r\n7.Online or on spot registration must be done.', 'Blesson G', '9043541643', 'Bharathkumar P', '8903212809', '08/02/2020', '10.00 AM ', '3.00 PM', 'Seminar hall-1', 1),
(16, 'Admin_cultural', 'E10016', 'Cultural', 'VILLAI-1 PHOTOGRAPHY(ON SPOT)', 'The art of photography is all about directing the attention of the viewer”. Here is the time for you budding photographers! Let people admire your photographs! Capture beauty around you but be sure not to get diverted from the theme. And, we are here for you guys, to appreciate the talent of photography in you. So, come disclose your talents to us!', '1)The event will be conducted on 6th February 2020.\r\n2)All the photos must be clicked in the SRI SHAKTHI CAMPUS.\r\n3)A new theme will be announced before the event.\r\n4.Photographs must be clicked from 9am-3pm.\r\n5)The maximum number of entries that a participant can submit is only one.\r\n6)Participants needs to submit the raw image along with their entry for submission(NO EDITING-STRICTLY).\r\n7)The photo should be original. PLAGIARISM of any kind will not be tolerated.\r\n8)The photo shouldn\'t be tampered.\r\n9)The photos can be taken only in DSLR.\r\n10)Participants photos can be in .jpg, .jpeg format.\r\n10)The decision of the judge will be final and binding.\r\n11)Flouting any of the above rules will lead to immediate DISQUALIFICATION.', 'Abinand', '9497578441', 'G J siddharth', '7397176300', '08/02/2020', '10.00 AM ', '3.00 PM', 'Open Auditorium', 1),
(17, 'Admin_cultural', 'E10017', 'Cultural', 'VILLAI-2 \r\nPHOTOGRAPHY(ONLINE)', 'Taking an image, freezing a moment, reveals how rich reality truly is.!\r\nHere is the time for you budding photographers. Let people admire your photographs !\r\nTheme: EMOTIONS\r\n', '* Likes will be considered. \r\n* We will post your photographs at our Instagram page : KALAM 2020 .\r\n* The decision of the judge will be final.\r\n* A brief presentation about the photo must be presented.\r\n\r\nRULES AND REGULATIONS: \r\n* It is an individual event.\r\n* Participants should submit only 1 photo.\r\n* Participants should mention their name &amp; institution along with their photographs in JPG or JPEG.\r\n* A One-line description about the photo is necessary.\r\n* The photographs submitted must be genuine, original work of the participant.\r\n* Either Mobile Phones or DSLR can be used.\r\n* Under any circumstance, entries once submitted cannot be taken back for modifications.\r\n* No watermark or any other form of marking should be seen on the image.\r\n* Edited pictures are not allowed. Exposure and colour corrections are allowed only upto a certain limit.\r\nEmail : kalam@siet.ac.in ', 'Abinand', '9497578441', 'G J siddharth', '7397176300', '08/02/2020', '10.00 AM ', '3.00 PM', 'Online', 1),
(18, 'Admin_biomedical', 'E10018', 'Technical', 'Workshop on &quot;RECENT TRENDS IN BIOMEDICAL INSTRUMENTATION&quot; \r\n(BME)', 'Practical and Lecture session on \'RECENT TRENDS IN BIOMEDICAL INSTRUMENTATION\' .', 'Basic knowledge in Biomedical Engineering.', 'Arya', '8075544838', 'Dr.R.V.Shalini', '8675303639', '06/02/2020', '10 am', '1 pm', 'LH 42&amp;BMI Laboratory', 1),
(19, 'Admin_biomedical', 'E10019', 'Technical', 'Tech Relay', 'It consist of 3 rounds which is based on technical aspects.\r\nRound 1-Boundy Hunter: This round is based on the assembling of various anatomical models.\r\nRound 2-Battle of Brains: Innovative solutions should be presented for the given problem statement.\r\nRound 3-Quiztery: This round is fully based on technical quiz.', '2 members per team.\r\nAccording to their involvement and answering skills in time ,they will be awarded.', 'Mownika', '8667440213', 'Mrs.P.Nancy', '9003337229', '06/02/2020', '2 pm', '4.30 pm', 'LH 34', 1),
(20, 'Admin_biomedical', 'E10020', 'Technical', 'Tricky Circuits', 'Tricky circuit is an event for innovative circuit designer .This will test your logical thinking and most importantly circuit designing skills. \r\nRound 1-Crossword Solver:Words should be framed from the given clues.\r\nRound 2-Lotto: To find out the correct circuit with the clues provided and mark them accordingly.\r\nRound 3- Circuit Builder: The teams will have to design the circuit for specified application with the given discrete components.', '2 members per team.\r\nBasic knowledge in electrical circuits. Participants are not allowed to use any electronic gadgets. The convener decision will be final. ', 'Mohanasundaram', '9025267616', 'Mrs.S.Christy Esther', ' 9710253292', '07/02/2020', '9.30 am', '12.30 pm', 'BMI laboratory', 1),
(21, 'Admin_biomedical', 'E10021', 'Technical', 'Dare to Do', 'This event is based on Biomedical Instrumentation that consists of 3 rounds.\r\nRound 1- Speed Up: The teams should do the given tasks(eg. operating a biomedical equipment and taking readings from it) and puzzles in the given time.\r\nRound 2-Jam: Team members should come forward individually and talk about the given topics for 2-5 minutes.\r\nRound 3- Technical Connexions: To find out the correct answer by connecting the given clues.', '2 members per team.\r\nBasic knowledge in Biomedical Instrumentation is must. All the tasks should be performed within given time and should have good communication skills.', 'Srivarsha', '7550381998', 'Ms.T.Gayathri', '9597494341', '07/02/2020', '1.30 pm', '4.30 pm', 'LH 34', 1),
(23, 'Admin_it', 'E10023', 'Technical', 'CODE SWAPPING', 'A group of two programmers writes program for two problems simultaneously. The programmers want to swap among themselves based on the swap time.', '\r\n1. Each Team will be provided two Windows based system.\r\n2. Compiling or debugging the code using any kind of applications is not permitted.\r\n3. The codes would be written in C/C++/JAVA/PYTHON (Based on participant)\r\n4. Any malpractice would lead to straight disqualification.\r\n5. There will be  three rounds', ' Annapoorni', '8220551086', ' P.Chinnasamy ', '9600281664', '07/02/2020', '10.00 AM', '4.30 PM', 'lab - 06', 1),
(24, 'Admin_biotech', 'E10024', 'Technical', 'Seminar', 'Biotechnology in 2030', 'Students should participate actively', 'Shanmuga Priya', '7010163080', 'Dr. R. Kannan', '8939944299', '06/02/2020', '9.30 AM', '12.30.PM', 'Seminar Hall 1', 1),
(25, 'Admin_biotech', 'E10025', 'Technical', 'Dock X', 'Molecular docking of protein-ligand using auto dock vina.\r\n\r\n', 'Requirement: Laptop is mandatory', 'Janane Meenatchi ', '7598726851', 'Mr.V. Venkataramanan', ' 9655065341', '06/02/2020', '2.00 PM', '4.30 PM', 'LH 34 A', 1),
(26, 'Admin_biotech', 'E10026', 'Technical', 'Streak Art', 'Students can streak a microorganism on agar plates with an art basis.', 'One per team', 'Akksadha M', '8220026129', 'Ms. G.Sri Thatchayani', '9042121790', '06/02/2020', '2.00 PM', '4.30 PM', 'Lab 2 (Biotech Department)', 1),
(27, 'Admin_biotech', 'E10027', 'Technical', 'Panoply', 'Students can come up with their projects and models developed with a start up idea based on life science.', '4 to 5 members in a team', 'Dr.R.Nirmal Kumar', '9994183582', 'Prasanth A', '9488664426', '06/02/2020', '9.30 AM', '12.30.PM', 'LH 30 &amp; LH 31', 1),
(28, 'Admin_biotech', 'E10028', 'Non Technical', 'Sherlock Holmes 2.0', 'Be the detective to solve a crime using forensics', 'Be the detective to solve a crime using forensics', 'Indu S', '9842239539', 'Mr. Harish B.S', '8489662360', '07/02/2020', '2.00 PM', '4.30 PM', 'Lab 1 (Biotech Department)', 1),
(29, 'Admin_Kalam', 'E10029', 'Technical', 'Final Test ok', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque in dictum non consectetur a erat. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Amet consectetur adipiscing elit ut aliquam purus sit amet. Interdum velit euismod in pellentesque massa  placerat. Euismod in pellentesque massa placerat. Nulla aliquet enim tortor at auctor urna nunc id. Enim tortor at auctor urna nunc id cursus metus. Montes nascetur ridiculus mus mauris.\r\n\r\nEnim blandit volutpat maecenas volutpat blandit. Arcu cursus vitae congue mauris rhoncus aenean vel. Amet est placerat in egestas erat  imperdiet. Egestas tellus rutrum tellus pellentesque. Interdum varius sit amet mattis vulputate enim. Suscipit adipiscing bibendum est ultricies integer quis. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Eget nunc lobortis mattis aliquam faucibus  purus in massa tempor. Curabitur vitae nunc sed velit dignissim. Enim neque volutpat ac tincidunt vitae. Dictumst quisque sagittis purus sit. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Pellentesque sit amet porttitor eget dolor morbi non arcu.  Morbi enim nunc faucibus a pellentesque sit. Neque sodales ut etiam sit amet nisl. Quam quisque id diam vel quam. Gravida quis blandit turpis cursus. Tortor posuere ac ut consequat.', '1. Enim blandit volutpat maecenas volutpat blandit.&amp;2.Arcu cursus vitae congue mauris rhoncus aenean vel.  Amet est placerat in egestas erat \r\n3imperdiet. Egestas tellus rutrum tellus pellentesque. Interdum varius sit amet mattis vulputate enim.\r\n4. Suscipit adipiscing bibendum est ultricies integer quis\r\n5.In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Eget nunc lobortis mattis aliquam faucibus  purus in massa tempor.\r\n6.Curabitur vitae nunc sed velit dignissim. Enim neque volutpat ac tincidunt vitae.\r\n7.Dictumst quisque sagittis purus sit. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque.\r\n8.Pellentesque sit amet porttitor eget dolor morbi non arcu.', 'Test', '1234567890', 'Test-2', '1234567890', '07/02/2020', '02:00 AM', '3:35 PM', 'Aerodome', 1),
(30, 'Admin_civil', 'E10030', 'Technical', 'CONNECTOR', 'A sequence of photos will be shown in a single slide of a power-point presentation. The teams have to connect the meaning in the picture to find the technical term that’s related to Civil Engineering', 'Team Members :2', 'Ajaykumar', '8940913288', 'Anitha J AP/civil', '8870209437', '06/02/2020', '2:30pm', '3:30pm', 'MELH12', 1),
(31, 'Admin_cultural', 'E10031', 'Cultural', 'KHOREO NIGHT 2020', 'This is the biggest Inter-collegiate dance competition in South India where the foremost dance teams of the country battle it out for \r\nthe top spot.', 'Registration Process :\r\n\r\nSend a minimum 3 minutes video to the  link &quot;khoreonight2020@gmail.com&quot; through google drive.\r\nVideo  submission last date 02.02.2020.\r\nIn the subject clearly mention the following \r\n• College Name         \r\n• Team Name \r\n• Theme and Non-Theme\r\nFor Example,Sub : SIET  Coimbatore_Illusion_Non Theme_Khoreonight2020.\r\nAlso fill in the form to confirm your interest in the event  &quot;https://forms.gle/ZjfWcLVvxZcuBMFy9&quot\r\n\r\nGeneral Rules :\r\nThe competition is divided into two categories - Theme and Non-Theme (Strictly western).\r\nEach category will be judged separately.\r\n• There is no restriction on the choice of song for Theme and  Non- Theme category.\r\n• All sequences performed on stage must be original. Any team found to have copied any part of their choreography, \r\nwill be disqualified.\r\n• The event consists of 2 rounds \r\nI. Round 1 – Online video entry. Only new choreographies will be allowed and not sequences which have been previously performed on the Kalam stage. The video must be a minimum of 3 mins. \r\nII .Round 2 – Performance at Kalam Khoreonight by teams shortlisted from Round 1.\r\n• Each team will be given a time slot of 8 minutes to perform and additional 30 sec for the setup and it is mandatory for \r\nevery performance to be a minimum of 4 minutes.\r\n• Minimum number of participants on stage at any time of the performance is 7. Maximum number of participants per team is \r\n30 plus a maximum of 2 backstage helpers.\r\n• Each team should consist of only current students (no alumni students allowed) of a particular college. Any team found to be\r\n violating this rule will be disqualified.\r\n • Any Obscene/Offensive music or Dialogues is not allowed.\r\n• Judges and coordinators decision will be final and binding. There shall be no arguments in this regard.\r\n', 'RANJITH ', '9944257595', 'MANIKANDAN', '9489566596', '07/02/2020', '05.00 PM ', '08.00 PM', 'Open Auditorium', 1),
(32, 'Admin_cultural', 'E10032', 'Cultural', 'SOLO DANCE [Western]', 'Dancers are made, not born. Join and let people see what you are made of! This is a western and eastern dance event that expects individual dancers to outlift the dancing spirit in them to the fullest. Are you dreaming of becoming the next Michael? The greatest audience awaits you at Kalam2020 !', '• This event consists of 2 rounds -\r\nI. Round 1 –Participants will perform to a track of their choice.The performance should be a minimum of 2 and \r\na maximum of 3 minutes. Round 1 will be conducted at the College Auditorium in the morning. \r\nII. Round 2 – Shortlisted dancers for round 2 will dance to any music played by DJ. The decision of the track played by the DJ is final. Request for change of track will not be entertained.\r\nGeneral Rules :\r\nParticipants are to be present at the event venue at least an hour before the start of the event.\r\n• Participants should bring their tracks in a pen drive.\r\n• Any dance style is accepted, and songs of any language can be used.\r\n• Slot picking will happen on a first come first serve basis.\r\n• Registration will be closed sharply at 10:30 AM, no one will be allowed to register after.\r\n• Dance performance should not convey any indecent gestures.\r\n • Any Obscene/Offensive music or Dialogues is not allowed.', 'RANJITH ', '9944257595 ', 'MANIKANDAN', '9489566596', '07/02/2020', '09.30 AM', '01.00 PM', 'Auditorium', 1),
(33, 'Admin_cultural', 'E10033', 'Cultural', 'GROUP DANCE[Eastern]', 'Indian classical dance is sustained by a profound philosophy. Form seeks to merge with the formless, motions seek to become a part \r\nof the motionless, and the dancing individual seeks to become one with the eternal dance of the cosmos.', '•Track should not be more than 3 min.\r\n•Participant should be present at the venue 30 min before the event for slot picking.\r\n•Vulgarity in terms of costumes or dialogues in the song will lead to disqualification.\r\n•The song should be brought in a pen drive and submitted to the organizers 30 min before the event.\r\n•Judges decision is final.', 'RANJITH ', '9944257595', 'MANIKANDAN', '9489566596', '08/02/2020', '09.30 AM', '01.00 PM', 'Auditorium', 1),
(34, 'Admin_cultural', 'E10034', 'Cultural', 'SOLO DANCE [Eastern]', 'Evoke with a sprinkle of dances”. Practice like you never WON, Perform like you never LOST. Mesmerize the onlookers with power,\r\n passion, and elegance. This event is a horde of dancers rocking with a style of their own as classical, braking, salsa, ballet, jazz etc… Showcase the type of dance that hides inside your every nerve and muscle. ', '*Minimum of 6 and a maximum of 25 participants per team. \r\n*Final Track length should not be more than 5-6 min (including narration). \r\n*The song should be loaded in a pen drive and submitted to the organizers 1hr before the event.\r\n*Slot picking will take place 1 hr before the event.\r\n*Vulgarity in terms of costumes or dialogues in the song will lead to disqualification.\r\n*The decision taken by the judges is final.', 'RANJITH', '9944257595', 'MANIKANDAN', '9489566596', '08/02/2020', '09.30 AM', '01.00 PM', 'Auditorium', 1),
(35, 'Admin_ece', 'E10035', 'Technical', 'Workshop on &quot;Current Trends in ASIC &amp; FPGA&quot;', 'Workshop on Current trends in ASIC and FPGA including validation and emulation.', 'Current trends in ASIC and FPGA including validation and emulation.', 'R.Ashokan                       (III ECE A)  ', '+91-8300247556', 'Mr.S. Siva Kumar, AP/ECE                 ', '+91-9578831343', '06/02/2020', '10.00am', '4.30pm', 'VLSI LAB', 1),
(36, 'Admin_cultural', 'E10036', 'Cultural', 'NIZHALPADAVI AWARDS', 'A short film is any motion picture not long enough to be considered a feature film.The increasingly rare industry term \r\n&quot;short subject&quot; carries more of an assumption that the film is shown as part of a presentation along with a feature film. Short films\r\n are often screened at local, national, or international film festivals and made by independent filmmakers with either a low budget or \r\nno budget at all.! ', '1) An entry free of Rs.300 will be charged per movie. \r\n2) Movies of any theme and category shall be submitted. \r\n3) The duration of the short film should not exeed 30 minutes. \r\n4) The film should have been shot/completed only after the 1st of January 2014, and should be submitted only by the rights holder\r\nof the film. \r\n5) The film can be in any language. \r\nEnglish subtitles is mandatory for films other than in Tamil language.\r\n6) The film should be submitted in full HD resolution.\r\n7) The participants should be aware of that the organisers are not responsible for any unauthorised use of the content by a third party.\r\n8) The decision of the Jury shall be final.\r\n9) Out of all entries, the shortlisted films will be screened during Nizhalpadavai Awards 2020 on the 6th of February 2020.\r\n10) Event organizers reserve the rights to change, modify or alter any rule, or a part of this event/competition at any point of time.\r\n11) The Best Film, The Best Director, The Best Actor, The Best Editor, The Best Writer, The Best DOP and The Best Movie With Hidden Details\r\n And Layers will be awarded.', 'Swaroop', '9952392615', 'G J Siddharth', '9944257595', '06/02/2020', '09.30 AM', '02.00PM', 'Auditorium', 1),
(37, 'Admin_it', 'E10037', 'Technical', 'Connection', '  Identify the technical words by connecting pictures displayed on the screen. ', '1. Maximum of two members per team.\r\n2.There will be three stages in this event.\r\n3. Internet access will not be provided\r\n4. Any malpractice would lead to straight disqualification.', 'Kavipriya', '7530013140', 'N.Priya', '9944052990', '07/02/2020', '10.00 AM', '12.00 PM', 'LH-24', 1),
(38, 'Admin_ece', 'E10038', 'Technical', 'Arduino contest', 'Innovative Project competition using Arduino related applications.', 'Three members per team. The project must be with Arduino kit. Students need to bring all the needed components as per their requirements.The maximum duration will be 2 hours.', 'Rahul J P (III ECE B) ', '+91 98002 66331', 'Mrs. S. Yogitha, AP/ECE ', '+91 91504 20556', '07/02/2020', '10:00 AM', '12:00 noon', 'RF Lab', 1),
(39, 'Admin_eee', 'E10039', 'Technical', 'DIY: Do it yourself', 'The participant will be allowed to see the picture of circuit/connections of the given device for 90 seconds and he/she has to memorize it. The participant will get 10 minutes to reassemble the given parts as shown.\r\n', 'Every team must consists of maximum two members.Team members should not use any notes, pen, mobile phones during the event. ROUNDS:The event consist of two rounds. The first round is reassembling the circuit. The second round is to reassemble the given appliance. The time taken to assemble will be noted.\r\n', 'Shivadharmanathan M U', '8056963189', 'Mr.B.Senthil Raja AP/EEE', '8754248090', '06/02/2020', '9.30 am', '11.00 am', 'Machines Lab', 1),
(40, 'Admin_eee', 'E10040', 'Technical', 'CIRCUIT DEBUGGING', 'Circuit Debugging is a technical event of finding and reducing the number of bugs or defects in an electronic circuit. Thus, making it behave as expected. Each team will be given a question sheet they\'ve to solve it within specified time.\r\n', '&quot;Every team should consist a maximum of TWO members.The decision of judges and event coordinators shall be treated as final and binding to all.A basic knowledge of digital and analog circuitry is necessary.\r\nThe event has THREE rounds which test your circuit debugging skills. ROUND 1:10 general aptitude and 10 simple electronics related questions will be given. ROUND 2:Participants who are selected to the second round are tested on their knowledge of digital circuitry.In this round 5 digital electronics questions will be given and they are supposed to identify the faults and rectify the circuit.In this round 5 analog circuit questions will also be given.Participants are supposed to find the bugs and solve them.\r\nROUND 3:Participants selected to this round are given a hardware circuit either digital or analog.Faults in the circuit should be identified to get the correct output.\r\n&quot;\r\n', 'Nivedha S', ' 8248043420', 'Dr.A.Kalaiarasi AP/EEE', '9842348280', '06/02/2020', '11.00 am', '12.30 pm', 'LH47', 1),
(41, 'Admin_eee', 'E10041', 'Technical', 'Device Cracking', 'The world of EEE is undergoing amazing developments technologically. So how much aware are you about your latest devices? Time to test it out. Different devices, different app’s, different circuits so let’s have fun with it. Just step in, crack the device and be in the spot light. Let`s see how well u crack it.\r\n', 'Each team consists of 2 participants. Rounds:• The event is categorized in to 4 rounds. • First round tests you on the basic knowledge you have in electrical terms. • Second round is a reasoning round in which you`ll have to justify a statement. • Third round is about how well you crack the devices shown. • Final round is to identify the function of circuit.\r\n', 'Gayathri N ', '6369275582', 'Mrs.P.Divyabanu AP/EEE', '7708037137', '06/02/2020', '3.00 pm', '4.30 pm', 'LH47', 1),
(42, 'Admin_eee', 'E10042', 'Technical', 'Project Presentation', 'Each student\'s research project &amp; presentation will be judged on its own merit in meeting the Criteria for Judging rather than in competition with other students project.\r\n', 'Each team consists of 4 participants. The presentation will not exceed a maximum time limit of ten (10) minutes. Upon completion of the presentation the researcher may be questioned BY THE JUDGES for a time period of NOT MORE THAN 5 MINUTES. Judges may ask questions to seek clarification of a student’s methods, conclusions, and/or understanding. The final working model of the project is to be displayed , where it will be judged by a panel of judges. Must be an original idea that aims to address social problems or gratifies industrial needs or satisfies any day to day utility, else for recreation.\r\n', 'Piradep P', '7639539539', 'Mr.Dhamodharan AP/EEE', '7395860647', '07/02/2020', '10.00 am', '4.30 pm', 'Machines Lab', 1),
(43, 'Admin_ece', 'E10043', 'Technical', 'Workshop on &quot;Embedded Automation&quot; (ECE)', 'The objective of this workshop is to give in-depth knowledge of 8-bit PIC Microcontroller with their programming so that participants can design real time projects on Embedded Systems (Home Automation, Home Security, Industrial Automation, Telecom, Automobile, Defence etc.) ', 'CONTENTS COVERING - PIC16F877A Microcontroller, Architecture, Pin diagram, MPLAB Software overview, Interfacing LED, Interfacing a Switch, Interfacing LED and Switch, Interfacing LCD , Traffic Light Control Algorithm using PIC16F877A Microcontroller, Analog sensor interface using PIC16F877A Microcontroller, Speed control of DC motor with PIC16F877A Microcontroller, Special task execution by PIC16F877A Microcontroller using interrupt concept.', 'D. Gokul Shakthi (III ECE A)  ', '+91-94877 55312', 'Mr.G.Kumaran, AP/ECE', '+91-99621 00958', '06/02/2020', '10.00am', '4.30pm', 'EMBEDDED LAB', 1),
(50, 'Admin_ece', 'E44596', 'Technical', 'Project Presentation (ECE)', 'Each student\'s research project &amp; presentation will be judged on its own merit in meeting the Criteria for Judging rather than in competition with other students project.', 'Each team consists of 4 participants. The presentation will not exceed a maximum time limit of ten (10) minutes. Upon completion of the presentation the researcher may be questioned BY THE JUDGES for a time period of NOT MORE THAN 5 MINUTES. Judges may ask questions to seek clarification of a student’s methods, conclusions, and/or understanding. The final working model of the project is to be displayed , where it will be judged by a panel of judges. Must be an original idea that aims to address social problems or gratifies industrial needs or satisfies any day to day utility, else for recreation.', '  M. Gowthaman (III ECE A)    ', '9566615244', 'Mr.Sivaprakasam, AP/ECE ', '9790038296', '07/02/2020', '10.00 am', '4.30 pm', 'Communication Lab, LIC Lab', 1),
(51, 'Admin_it', 'E82862', 'Technical', ' WORKSHOP ON MACHINE LEARNING', 'One-day workshop on machine learning using python by “ Innovace  solutions”.', '1.Registration is mandatory\r\n2.Participants be on time ', ' Arvind', '9790231765', 'S.WilsonPrakash ', '8300112789', '06/02/2020', '9.30 AM', '4.30 PM', 'LAB-06', 1),
(52, 'Admin_mech', 'E36103', 'Technical', 'USE CASE ANALYSIS', 'Providing an opportunity for student researchers to disseminate their ideas in various fields of mechanical engineering. Industrial problems will be given and students need to bring with advance solutions', '•	A Team of two members are allowed to participate in this event.\r\n•	Industry use cases will be given on the spot for which innovative and feasible solution must be given by the team.\r\n•	A specified time will be given for the team to develop and present their idea which includes the following\r\n	Creative idea\r\n	Conceptual design using CAD software (Solidworks)\r\n•	The facilities for CAD modelling will be provided by the college.\r\n•	The points will be awarded based on the feasibility of the solution and cost effectiveness.\r\n', 'SAI KRISHNA', '9884426651', ' Dr. S.M.Rajkumar', '9487981645', '06/02/2020', '09.00 AM', '04.00 PM', 'CAD LAB', 1),
(53, 'Admin_mech', 'E47593', 'Technical', 'PROJECT EXPO', 'PRESENT YOUR CREATIVE IDEAS THROUGH HARDWARE THAT SHOULD HAVE SOCIAL RELEVANCE', '•	Each team must have maximum of 3 members.\r\n•	A team member must participate in only one project presentation.\r\n•	The project should consists of hardware.\r\n•	The project should have social relevance\r\n', 'RAJ KUMAR', '8760784897', 'Mr. R. Prakash ', '9786197062', '06/02/2020', '09.00 AM', '12.00 PM', 'MECHNICAL DEPARTMENT', 1),
(54, 'Admin_mech', 'E27700', 'Technical', 'SPROCKET RAJA', 'Get ready to get your hands all greased up. Re-Assemble and take the machine back to its old glory with in the break hits. And you will be crowned as the Sprocket Raja.Earn the tittle and grab the loot', '•	It’s a Team Event that should have two members in a team.\r\n•	A Product will be given in a dismantled form; participants should reassemble the given part back to its original condition in a given duration of time.\r\n•	Mild steel will be given as work piece\r\n•	As per the requirement in design the work piece should be machined using several operations according to the needs.\r\n•	Points will be given based on the assembled part accuracy and time taken for it.\r\n\r\n', 'ROHAN STEEL', '9245861222', 'Mr.M. Rajsekar', '9524530048', '07/02/2020', '9.00 AM', '12.00 PM', 'MANUFACTURING LAB', 1),
(55, 'Admin_mech', 'E77152', 'Technical', 'WORKSHOP ON INDUSTRY 4.0', 'Industry 4.0 is the current trend of automation and data exchange in manufacturing technologies. It includes cyber-physical systems, the Internet of things and cloud computing. Industry 4.0 creates what has been called a &quot;smart factory&quot;. This workshop introduces the participants to current Industry trends and advancements in the areas of Manufacturing Technologies.', 'INDIVIDUALS WISH TO GRAB CURRENT INDUSTRY TRENDS AND ADVANCEMENTS IN THE AREA OF MANUFACTURING CAN TAKE PART. ', 'ESWARAN', '8870940224', 'Mr. Mr. S. Gnanasekaran', '9789611628', '07/02/2020', '09.30 AM', '4.00 PM', 'SEMINAR HALL 2', 1),
(56, 'Admin_foodtech', 'E54290', 'Technical', 'Food teckers', 'FOOD TECKERS is a Project or a model Presentation event in which the participants will present with their final product/model/prototype or 3D designs  relating Food Technology and its related field.', 'Two Members in a Group\r\nThe concept must be relevant to food Technology and its related field . It should be novel and social relevant. The participant must justify the impact of the proposed idea.\r\n\r\n1)The participants must bring the proposed product along with the power point presentation based on the below details \r\n2)The power point presentation must contain up-to 20 slides \r\n3)Time allotted for each group (10 - 15 minutes ) \r\n4)Font style:Times New Roman  \r\n5)The concept must be clear and precise \r\n6)Participants should report the venue at 10:45 AM ', 'Pranav MS', '8113049075', 'Er.S.Sujithra', '6382687459', '07/02/2020', '11:00 AM', '12:30 PM', 'Department of food technology', 1),
(57, 'Admin_cultural', 'E65178', 'Cultural', 'PARAI', 'By drumming this drum they use to gather people at one place and deliver the message at once. Later the drum associated with the dance\r\n form Parai Attam.', '•This  competition is open to all the college students.\r\n•Participants should perform any three from the syllabus and two of their own choice.\r\n•Ornaments should be avoided.\r\n•The winners, who secure first two places in both male and female groups will be awarded with cash prize and a certificate.\r\n•The participants who perform the perfect posture for the given time will be declared as winners', 'Divya Bharathi', '7502175274', 'Dhayaanidhi J G', '8667843286', '08/02/2020', '10.00 AM ', '01.00 PM', 'Drawing Hall', 1),
(58, 'Admin_foodtech', 'E53627', 'Technical', 'Cease the Case', 'Cease the case is the event in which the participants will suggest solution for the industrial problems posed by Industrial persons.', 'No. of Participants: \r\nMin 1, Max. 4\r\n1.Problem statements will be provided prior few days of the event, \r\n2.The participants should present the solution in the Powerpoint presentation. The solution can be in the form of  DIAGRAMS /FLOWSHEET.\r\n3.The solution to the problems must be feasible, there will be an interactive session between the INDUSTRIAL person and the PARTICIPANTS of  Individual presentation.\r\n4. The participants should assemble before 20 minutes from the start of the event.', 'Naveen Natarajan.V', '6381505919', 'Er.S.Nithya Bala Sundari', '9566360985', '07/02/2020', '1:30 PM', '3:00 PM', 'Department of food technology', 1),
(59, 'Admin_cultural', 'E28441', 'Cultural', 'SILAMBAM', 'Courage is not the absence of fear, but the triumph over it.', '•This  competition is open to all the college students.\r\n•Participants should perform any three from the syllabus and two of their own choice.\r\n•Ornaments should be avoided.\r\n•The winners, who secure first two places in both male and female groups will be awarded with cash prize and a certificate.\r\n•The participants who perform the perfect posture for the given time will be declared as winners', 'Karthika', '9344797063', 'Swaroop', '9952392615', '08/02/2020', '10.00 AM  ', '01.00 PM', 'Drawing Hall', 1),
(60, 'Admin_foodtech', 'E62164', 'Technical', 'Ersatz', 'ERSATZ is an adulterant identification event in which the participants detect the presence of adulterant in the food material The participants will be given food sample to detect the presence of adulterant ', 'No. of Participants: 2 members \r\nThe participants must identify the adulterant present in the given food material.\r\n1)There will be three levels in this event \r\n2)Participants must identify the presence of adulterant in the given time\r\n3)Participants must report the venue before 2:00 PM \r\n', 'Sree Sowbagiya G', '8300528594', 'Dr.Allwyn Sundarraj', '9443997989', '07/02/2020', '2:00 PM', '5:00 PM', 'Department of food technology', 1),
(61, 'Admin_civil', 'E61787', 'Non Technical', 'IPL AUCTION', 'Players to auctioned are chosen and their base price is set, and these players are bought by the franchise that bids the highest for them', '\r\n1. The limit of overseas players should not exceed more than 8 members in the squad and more than 4 members in the playing XI. \r\n2. Only a max of 17 players should be picked up in the auction. \r\n3. Teams will be disqualified if they exceed the given budget of 70cr. \r\n4. Fair play and discipline should be maintained, Teams should obey the auctioneer. \r\n5. Presence of an uncapped player in the playing XI is mandatory. \r\n6. If a player goes for more than 20cr in the auction, then the teams raising the bid for the player will be considered and the player will be sold for 20cr to a team that wins in chit shuffling. \r\n7. The auction may take few long hours and there will be a quick 10min break in between. \r\n8. The auction will be so swift that the teams should raise the bid without taking much time and the auctioneer will sell the players quickly. \r\n9. The players unsold in the auction will be recalled again in the end of the auction. \r\n\r\n', 'ARAVIND', '7397087567', 'ARAVIND', '7397087567', '06/02/2020', '10:00AM', '3:30PM', 'FOOD COURT', 1),
(62, 'Admin_eee', 'E66420', 'Technical', 'Workshop on &quot;Embedded Automation&quot;(EEE)', 'The objective of this workshop is to give in-depth knowledge of 8-bit PIC Microcontroller with their programming so that participants can design real time projects on Emebdded Systems (Home Automation, Home Security, Industrial Automation, Telecom, Automobile, Defence etc.)', 'PIC16F877A Microcontroller, Architecture, Pin diagram, MPLAB Software overview, Interfacing LED, Interfacing a Switch, Interfacing LED and Switch, Interfacing LCD , Traffic Light Control Algorithm using PIC16F877A  Microcontroller, Analog sensor interface using PIC16F877A  Microcontroller, Speed control of DC motor with PIC16F877A Microcontroller, Special task execution by PIC16F877A Microcontroller using interrupt concept.', 'Srinaya V', '9487755312', 'Dr .N. Prabhakaran  AP/EEE', '9514240782', '06/02/2020', '10.00 am', '4.30 pm', 'EMBEDDED LAB', 1),
(63, 'Admin_foodtech', 'E86586', 'Technical', 'Seminar on Food Processing and its Challenges', 'General seminar based on New Trends and Challenges in food industry', '-', 'Varshini ', '9791719965', 'Er.Durga Devi', '8807612177', '06/02/2020', '10:00 AM ', '12:00 PM', 'Department of food technology', 1),
(64, 'Admin_foodtech', 'E77321', 'Technical', 'Workshop on sugar crafts', 'Sugar crafts is the art of creating confectionery or cake decorations from sugar paste. By this workshop the participants will acquire the skills and experience needed to work on sugar or gum paste. ', 'Batch: 20 members\r\n The participants will undergo hands on training. ', 'Raagavarshini ', '8754677866', 'Er.R.S.Gaudham', '9953580606', '06/02/2020', '1:30 PM', '4:00 PM', 'Department of food technology', 1),
(65, 'Admin_cse', 'E26383', 'Technical', 'HACKATHON 20', 'A non stop 24 hour product development contest to be conducted on February 6th and 7th. Student teams across various colleges are expected to participate in this contest to develop mobile, web applications and IOT prototypes. ', '&quot;1. 3 members per team, inter department, inter collegiate teams allowed.\r\n2. Teams are expected to develop a product (mobile app, web app or IoT app) in 24 hours as per the given problem statements.\r\n3. Internet connection, power supply points, dinner and snacks will be provided.\r\n4. All necessary hardware and software should be brought by the teams.&quot;', 'bharath', '8903212809', 'Uma maheshwari', '9597255534', '06/02/2020', '10.00 AM ', '10.00 PM', 'Ball Room', 1),
(66, 'Admin_cse', 'E77109', 'Technical', 'Programming Contest', 'Competitive Programming is the most preferred way for the Industry to assess the coding skills of the student. The students will be solving the problems of various difficulty levels. The student developers will be challenged with real life problems. ', '•        The contest is open to anyone with a flair for programming.\r\n•        Maximum of two members per team is allowed to participate.\r\n•        Anyone with a HackerRank account will be eligible to take part in the contest. If you do not have a HackerRank account yet, create one before entering the contest.\r\n•        A participant shall be part of only one team.\r\n•        Provision of computer and access to internet will be ensured by us.\r\n•        Both the team members should solve the questions in a programming language known by both of them.\r\n•        Plagiarism is not encouraged.\r\n•        No electronic gadgets will be allowed inside the contest venue.\r\n•        Contestants will be provided a sheet of paper  for rough use.\r\n•        We hold the right to disqualify any team that gets involved in malicious activity during the contest.\r\n', 'bharath', '8903212809', 'P.Suvitha Vani    ', ' 9790995882 ', '07/02/2020', '10.00 AM ', '01.00 PM', 'Lab 2', 1),
(67, 'Admin_agri', 'E37792', 'Technical', 'FIT', 'Participants should Attach the given implements in tractor and demonstrate the operation. ', 'Team consists of maximum two members. Maximum time of ten minutes will be given for attaching and demonstration. ', 'PRAKASH.D', '9080540476', 'Dr. Edwin Benjamin', '8907780447', '06/02/2020', '9.30 am', '3.00 pm', 'Farm Machine Lab', 1),
(68, 'Admin_agri', 'E99997', 'Technical', 'Project Expo (Blitz)', 'Students will exhibit their projects. Industrialists will be judging.', 'Participants Should Demonstrate Their Projects Infront of Industrialist.', 'Rohith Nambhiar', '7034203285', 'Mr.Vignesh Kumar ', '9994612452', '06/02/2020', '10.00 AM', '3.00 PM', 'LH 5', 1),
(69, 'Admin_agri', 'E25583', 'Technical', 'Dream Farm (Farm layout)', 'Participants have to draw a layout of agricultural farm with necessary details of a farm. The instruction about the farm will be given on spot. ', 'should use only A3 sheets.  \r\nparticipants should use pencils only', 'Sabarinadhan/Muthu Kumar', '8807789773', 'Mr.Thousiff', '9842610097', '06/02/2020', '10.00 AM', '3.00 pm', 'DRAWING HALL', 1),
(70, 'Admin_agri', 'E79838', 'Technical', 'Solid Master', 'Participants have to develop a concept and should provide their design solution. the concept and problem statements will be provided on spot based on the industry need. ', 'Should draw by using Solid Work, Maximum time of one hour will be given. The judgement will be done by industry person only based on the given problem statement. ', 'Praveen Kumar S/Prabhu Raj', '8682823025', 'Mr.N Vignesh Kumar', '9994612452', '07/02/2020', '10.00 AM', '3.00 pm', 'CAD Lab 14/15', 1);
INSERT INTO `event_details` (`id`, `admin_id`, `event_id`, `category`, `event_name`, `description`, `event_rules`, `student_coordinator_name`, `student_coordinator_number`, `staff_coordinator_name`, `staff_coordinator_number`, `event_date`, `event_start_time`, `event_end_time`, `venue`, `status`) VALUES
(71, 'Admin_agri', 'E23840', 'Technical', 'Identification of machine parts', 'Participants have to identify the machine parts given on the spot.', 'Participants should identify the given machine parts in given time\r\nmobile phones are strictly prohibited', 'PRAMODH S.P\\SURYA KUMAR T.M', '8248821956', 'Dr. Edwin Benjamin', '8907780447', '07/02/2020', '10.00 AM', '3.00 pm', 'Farm Machine Lab', 1),
(72, 'Admin_agri', 'E54661', 'Non Technical', 'DREAM11', 'Participants should select the best 11 team\r\nTeam selection is based on auction', 'A Team should consists of atleast 4 members\r\nBest team will be rewarded', 'TAMIL SELVAN\\PRABHU RAJ', '8825799908', 'MR.SHANMUGA SUNDARAM', '9943338338', '06/02/2020', '10.00 AM', '3.00 PM', 'LH 6', 1),
(73, 'Admin_agri', 'E34959', 'Non Technical', 'BOWLED OUT', 'PARTICIPANTS SHOULD HIT THE STUMPS USING TENNIS BALL\r\n3 CHANCES WILL BE GIVEN', 'BALL WILL BE PROVIDED\r\n', 'SASIKUMAR\\PRASANTH', '8760709721', 'DR.VIDHU PRABHA', '8825799908', '06/02/2020', '9.00 AM', '3.00 pm', 'NEAR FOOD COURT', 1),
(74, 'Admin_agri', 'E77411', 'Non Technical', 'IDENTIFICATION OF FOOD PRODUCTS', 'PARTICIPANTS HAVE TO IDENTIFY AND NAME THE FOOD PRODUCTS BY TASTING', 'PARTICIPANTS SHOULD NOT  TOUCH THE FOOD PRODUCTS', 'VAISHA RESHMI\\KOWSALYA', '6374347056', 'NAGESWARI', '9080993904', '06/02/2020', '9.00 AM', '3.00 pm', 'NEAR FOOD COURT', 1),
(75, 'Admin_cultural', 'E61660', 'Cultural', 'MIMICRY', 'Every class has pupils who mimic the teachers particularly well and perform for their classmates; a class without such teacher-mimics would \r\nhave something lifeless about it.', 'The performance should be within 5 min\r\nThe participant should be praticed well\r\nJudges decision will be final', 'GOWTHAM RAM', '8072758059', 'Bharathkumar', '8903212809', '08/02/2020', '10.00 AM ', '02.00PM', 'Seminar hall-2', 1);

-- --------------------------------------------------------

--
-- Table structure for table `participant_login`
--

CREATE TABLE `participant_login` (
  `login_id` int(11) NOT NULL,
  `Kalam_id` varchar(100) DEFAULT NULL,
  `email` varchar(30) NOT NULL,
  `full_name` varchar(30) NOT NULL,
  `department` varchar(20) NOT NULL,
  `year` varchar(10) NOT NULL,
  `college` varchar(40) NOT NULL,
  `password` varchar(300) NOT NULL,
  `status` int(1) NOT NULL DEFAULT 1,
  `mob_no` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `participant_login`
--

INSERT INTO `participant_login` (`login_id`, `Kalam_id`, `email`, `full_name`, `department`, `year`, `college`, `password`, `status`, `mob_no`) VALUES
(1, 'KALAM52546', 'samcladson08@gmail.com', 'sam cladson', 'CSE', '3rd year', 'SIET', 'sam', 1, 2147483647),
(2, 'KALAM11590', 'jeevan@gmail.com', 'Jeevan', 'cse', '3rd year', 'SRIPC', 'cse', 1, 987765654);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `department_admin`
--
ALTER TABLE `department_admin`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `events_registration`
--
ALTER TABLE `events_registration`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `event_details`
--
ALTER TABLE `event_details`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `event_id` (`event_id`);

--
-- Indexes for table `participant_login`
--
ALTER TABLE `participant_login`
  ADD PRIMARY KEY (`login_id`,`email`),
  ADD UNIQUE KEY `email` (`email`),
  ADD UNIQUE KEY `Kalam_id` (`Kalam_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `department_admin`
--
ALTER TABLE `department_admin`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- AUTO_INCREMENT for table `events_registration`
--
ALTER TABLE `events_registration`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `event_details`
--
ALTER TABLE `event_details`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=76;

--
-- AUTO_INCREMENT for table `participant_login`
--
ALTER TABLE `participant_login`
  MODIFY `login_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
