export const matchingStars = {
  Revathi: 10,
  Uthirattathi: 8,
  Bharani: 8,
  Poosam: 8,
  Thiruvonam: 8,
  Chathayam: 8,
  Thiruvathirai: 8,
  Aswini: 7,
  Rohini: 7,
  Mirugasheerisham: 7,
  Swathi: 7,
  Pooram: 6,
  Hastham: 6,
  Kettai: 6,
  Pooraadam: 6,
  Anusham: 5,
  Makam: 4,
} as const;

export const StateList = ['Tamil Nadu', 'Kerala', 'Karnataka'] as const;

export const DistrictList = {
  'Tamil Nadu': [
    'Ariyalur',
    'Chengalpattu',
    'Chennai',
    'Coimbatore',
    'Cuddalore',
    'Dharmapuri',
    'Dindigul',
    'Erode',
    'Kallakurichi',
    'Kanchipuram',
    'Kanyakumari',
    'Karur',
    'Krishnagiri',
    'Madurai',
    'Mayiladuthurai',
    'Nagapattinam',
    'Namakkal',
    'Perambalur',
    'Pudukkottai',
    'Ramanathapuram',
    'Ranipet',
    'Salem',
    'Sivaganga',
    'Tenkasi',
    'Thanjavur',
    'Theni',
    'Thiruvallur',
    'Thiruvarur',
    'Thiruvannamalai',
    'Thoothukudi (Tuticorin)',
    'Tiruchirappalli (Trichy)',
    'Tirunelveli',
    'Tirupathur',
    'Tiruppur',
    'Vellore',
    'Viluppuram',
    'Virudhunagar',
  ],
  Kerala: [
    'Alappuzha',
    'Ernakulam',
    'Idukki',
    'Kannur',
    'Kasaragod',
    'Kollam',
    'Kottayam',
    'Kozhikode',
    'Malappuram',
    'Palakkad',
    'Pathanamthitta',
    'Thiruvananthapuram',
    'Thrissur',
    'Wayanad',
  ],
  Karnataka: [
    'Bagalkot',
    'Ballari (Bellary)',
    'Belagavi (Belgaum)',
    'Bengaluru Rural',
    'Bengaluru Urban',
    'Bidar',
    'Chamarajanagar',
    'Chikkaballapur',
    'Chikkamagaluru (Chikmagalur)',
    'Chitradurga',
    'Dakshina Kannada',
    'Davanagere',
    'Dharwad',
    'Gadag',
    'Hassan',
    'Haveri',
    'Kalaburagi (Gulbarga)',
    'Kodagu',
    'Kolar',
    'Koppal',
    'Mandya',
    'Mysuru (Mysore)',
    'Raichur',
    'Ramanagara',
    'Shivamogga (Shimoga)',
    'Tumakuru (Tumkur)',
    'Udupi',
    'Uttara Kannada (Karwar)',
    'Vijayapura (Bijapur)',
    'Yadgir',
  ],
} as const;

export const zodiacSignList = {
  aries: { english: 'Aries', tamil: 'மேஷம்', tanglish: 'Mesham' },
  taurus: { english: 'Taurus', tamil: 'ரிஷபம்', tanglish: 'Rishabam' },
  gemini: { english: 'Gemini', tamil: 'மிதுனம்', tanglish: 'Mithunam' },
  cancer: { english: 'Cancer', tamil: 'கடகம்', tanglish: 'Kadagam' },
  leo: { english: 'Leo', tamil: 'சிம்மம்', tanglish: 'Simmam' },
  virgo: { english: 'Virgo', tamil: 'கன்னி', tanglish: 'Kanni' },
  libra: { english: 'Libra', tamil: 'துலாம்', tanglish: 'Thulaam' },
  scorpio: { english: 'Scorpio', tamil: 'விருச்சிகம்', tanglish: 'Viruchigam' },
  sagittarius: { english: 'Sagittarius', tamil: 'தனுசு', tanglish: 'Dhanusu' },
  capricorn: { english: 'Capricorn', tamil: 'மகரம்', tanglish: 'Makaram' },
  aquarius: { english: 'Aquarius', tamil: 'கும்பம்', tanglish: 'Kumbam' },
  pisces: { english: 'Pisces', tamil: 'மீனம்', tanglish: 'Meenam' },
} as const;

export const PROFILE_STATUS = {
  NEW: 'New',
  REJECTED: 'Rejected',
  CONTACTED: 'Contacted',
  MEETING_SCHEDULED: 'Meeting Scheduled',
  ACCEPTED: 'Accepted',
  ON_HOLD: 'OnHold',
  PROFILE_SHARED: 'Profile Shared',
} as const;

export const PROFILE_STATUS_COLORS = {
  NEW: 'bg-teal-100 text-teal-800',
  REJECTED: 'bg-red-100 text-red-800',
  CONTACTED: 'bg-blue-100 text-blue-800',
  MEETING_SCHEDULED: 'bg-green-100 text-green-800',
  ACCEPTED: 'bg-green-100 text-green-800',
  ON_HOLD: 'bg-yellow-100 text-yellow-800',
  PROFILE_SHARED: 'bg-purple-100 text-purple-800',
} as const;
