export const MATCHING_STARS = {
  Aswini: 8,
  Bharani: 8,
  Poosam: 8,
  Swathi: 9,
  Kettai: 8,
  Uthirattathi: 8,
  Revathi: 9,
} as const;

export const StateList = ['Tamil Nadu', 'Kerala', 'Karnataka'] as const;

export const DistrictList = {
  'Tamil Nadu': [
    'Ariyalur',
    'Chengalpattu',
    'Chennai',
    'Coimbatore',
    'Cuddalore',
    'Dharmapuri',
    'Dindigul',
    'Erode',
    'Kallakurichi',
    'Kanchipuram',
    'Kanyakumari',
    'Karur',
    'Krishnagiri',
    'Madurai',
    'Mayiladuthurai',
    'Nagapattinam',
    'Namakkal',
    'Perambalur',
    'Pudukkottai',
    'Ramanathapuram',
    'Ranipet',
    'Salem',
    'Sivaganga',
    'Tenkasi',
    'Thanjavur',
    'Theni',
    'Thiruvallur',
    'Thiruvarur',
    'Thiruvannamalai',
    'Thoothukudi (Tuticorin)',
    'Tiruchirappalli (Trichy)',
    'Tirunelveli',
    'Tirupathur',
    'Tiruppur',
    'Vellore',
    'Viluppuram',
    'Virudhunagar',
  ],
  Kerala: [
    'Alappuzha',
    'Ernakulam',
    'Idukki',
    'Kannur',
    'Kasaragod',
    'Kollam',
    'Kottayam',
    'Kozhikode',
    'Malappuram',
    'Palakkad',
    'Pathanamthitta',
    'Thiruvananthapuram',
    'Thrissur',
    'Wayanad',
  ],
  Karnataka: [
    'Bagalkot',
    'Ballari (Bellary)',
    'Belagavi (Belgaum)',
    'Bengaluru Rural',
    'Bengaluru Urban',
    'Bidar',
    'Chamarajanagar',
    'Chikkaballapur',
    'Chikkamagaluru (Chikmagalur)',
    'Chitradurga',
    'Dakshina Kannada',
    'Davanagere',
    'Dharwad',
    'Gadag',
    'Hassan',
    'Haveri',
    'Kalaburagi (Gulbarga)',
    'Kodagu',
    'Kolar',
    'Koppal',
    'Mandya',
    'Mysuru (Mysore)',
    'Raichur',
    'Ramanagara',
    'Shivamogga (Shimoga)',
    'Tumakuru (Tumkur)',
    'Udupi',
    'Uttara Kannada (Karwar)',
    'Vijayapura (Bijapur)',
    'Yadgir',
  ],
} as const;

export const zodiacSignList = {
  aries: {
    english: 'Aries',
    tanglish: 'Mesham',
    order: 1,
    stars: ['Aswini', 'Bharani', 'Karthikai'],
  },
  taurus: {
    english: 'Taurus',
    tanglish: 'Rishabam',
    order: 2,
    stars: ['Karthigai', 'Rohini', 'Mirugasheerisham'],
  },
  gemini: {
    english: 'Gemini',
    tanglish: 'Mithunam',
    order: 3,
    stars: ['Mrigaseersham', 'Thiruvathirai', 'Punarvasu'],
  },
  cancer: {
    english: 'Cancer',
    tanglish: 'Kadagam',
    order: 4,
    stars: ['Punarpoosam', 'Poosam', 'Ayilyam'],
  },
  leo: {
    english: 'Leo',
    tanglish: 'Simmam',
    order: 5,
    stars: ['Makam', 'Pooram', 'Uthiram'],
  },
  virgo: {
    english: 'Virgo',
    tanglish: 'Kanni',
    order: 6,
    stars: ['Uthiram', 'Astam', 'Chithirai'],
  },
  libra: {
    english: 'Libra',
    tanglish: 'Thulaam',
    order: 7,
    stars: ['Chithirai', 'Swathi', 'Visagam'],
  },
  scorpio: {
    english: 'Scorpio',
    tanglish: 'Viruchigam',
    order: 8,
    stars: ['Visagam', 'Anusham', 'Kettai'],
  },
  sagittarius: {
    english: 'Sagittarius',
    tanglish: 'Dhanusu',
    order: 9,
    stars: ['Moolam', 'Pooradam', 'Uthiradam'],
  },
  capricorn: {
    english: 'Capricorn',
    tanglish: 'Makaram',
    order: 10,
    stars: ['Uthiradam', 'Thiruvonam', 'Avittam'],
  },
  aquarius: {
    english: 'Aquarius',
    tanglish: 'Kumbam',
    order: 11,
    stars: ['Dhanishta', 'Sadayam', 'Poorattathi'],
  },
  pisces: {
    english: 'Pisces',
    tanglish: 'Meenam',
    order: 12,
    stars: ['Purva Bhadrapada', 'Uthirattathi', 'Revathi'],
  },
} as const;

export const PROFILE_STATUS = {
  NEW: 'New',
  REJECTED: 'Rejected',
  CONTACTED: 'Contacted',
  MEETING_SCHEDULED: 'Meeting Scheduled',
  ACCEPTED: 'Accepted',
  ON_HOLD: 'OnHold',
  PROFILE_SHARED: 'Profile Shared',
  NEED_TO_CONTACT: 'Need to Contact',
  SHARE_BY_RM: 'Share by RM',
} as const;

export const PROFILE_STATUS_COLORS = {
  NEW: 'bg-sky-100 text-sky-700',
  REJECTED: 'bg-rose-100 text-rose-700',
  CONTACTED: 'bg-indigo-100 text-indigo-700',
  MEETING_SCHEDULED: 'bg-lime-100 text-lime-700',
  ACCEPTED: 'bg-emerald-100 text-emerald-700',
  ON_HOLD: 'bg-amber-100 text-amber-700',
  PROFILE_SHARED: 'bg-fuchsia-100 text-fuchsia-700',
  SHARE_BY_RM: 'bg-orange-100 text-orange-700',
  NEED_TO_CONTACT: 'bg-slate-200 text-slate-700',
} as const;
