export const MATCHING_STARS = {
  Ashwini:     6,
  Bharani:     8,
  Krittika:    3,
  Rohini:      8,
  Mrigasira:   4,
  Ardra:       6,
  Punarpoosam: 3,
  Poosam:      6.5,
  Ayilyam:     7,
  Magam:       4,
  Pooram:      6,
  Uthiram:     3,
  Hastham:     7,
  Chithirai:   4,
  Swati:       6,
  Visakam:     3,
  Anusham:     6.5,
  Kettai:      4,
  Moolam:      3,
  Pooradam:    8,
  Uthiradam:   2,
  Thiruvonam:  7,
  Avittam:     7,
  Sadhayam:    6,
  Poorattadhi: 3,
  Uthirattadhi: 8.5,
  Revathi:     7,
} as const;

export const STATE_LIST = ['Tamil Nadu', 'Kerala', 'Karnataka'] as const;

export const DISTRICT_LIST = {
  'Tamil Nadu': [
    'Ariyalur',
    'Chengalpattu',
    'Chennai',
    'Coimbatore',
    'Cuddalore',
    'Dharmapuri',
    'Dindigul',
    'Erode',
    'Kallakurichi',
    'Kanchipuram',
    'Kanyakumari',
    'Karur',
    'Krishnagiri',
    'Madurai',
    'Mayiladuthurai',
    'Nagapattinam',
    'Namakkal',
    'Perambalur',
    'Pudukkottai',
    'Ramanathapuram',
    'Ranipet',
    'Salem',
    'Sivaganga',
    'Tenkasi',
    'Thanjavur',
    'Theni',
    'Thiruvallur',
    'Thiruvarur',
    'Thiruvannamalai',
    'Thoothukudi (Tuticorin)',
    'Tiruchirappalli (Trichy)',
    'Tirunelveli',
    'Tirupathur',
    'Tiruppur',
    'Vellore',
    'Viluppuram',
    'Virudhunagar',
  ],
  Kerala: [
    'Alappuzha',
    'Ernakulam',
    'Idukki',
    'Kannur',
    'Kasaragod',
    'Kollam',
    'Kottayam',
    'Kozhikode',
    'Malappuram',
    'Palakkad',
    'Pathanamthitta',
    'Thiruvananthapuram',
    'Thrissur',
    'Wayanad',
  ],
  Karnataka: [
    'Bagalkot',
    'Ballari (Bellary)',
    'Belagavi (Belgaum)',
    'Bengaluru Rural',
    'Bengaluru Urban',
    'Bidar',
    'Chamarajanagar',
    'Chikkaballapur',
    'Chikkamagaluru (Chikmagalur)',
    'Chitradurga',
    'Dakshina Kannada',
    'Davanagere',
    'Dharwad',
    'Gadag',
    'Hassan',
    'Haveri',
    'Kalaburagi (Gulbarga)',
    'Kodagu',
    'Kolar',
    'Koppal',
    'Mandya',
    'Mysuru (Mysore)',
    'Raichur',
    'Ramanagara',
    'Shivamogga (Shimoga)',
    'Tumakuru (Tumkur)',
    'Udupi',
    'Uttara Kannada (Karwar)',
    'Vijayapura (Bijapur)',
    'Yadgir',
  ],
} as const;

export const ZODIAC_SIGN_LIST = {
  aries: {
    english: 'Aries',
    tanglish: 'Mesham',
    order: 1,
    stars: ['Ashwini', 'Bharani', 'Krittika'],
  },
  taurus: {
    english: 'Taurus',
    tanglish: 'Rishabam',
    order: 2,
    stars: ['Krittika', 'Rohini', 'Mrigasira'],
  },
  gemini: {
    english: 'Gemini',
    tanglish: 'Mithunam',
    order: 3,
    stars: ['Mrigasira', 'Ardra', 'Punarpoosam'],
  },
  cancer: {
    english: 'Cancer',
    tanglish: 'Kadagam',
    order: 4,
    stars: ['Punarpoosam', 'Poosam', 'Ayilyam'],
  },
  leo: {
    english: 'Leo',
    tanglish: 'Simmam',
    order: 5,
    stars: ['Magam', 'Pooram', 'Uthiram'],
  },
  virgo: {
    english: 'Virgo',
    tanglish: 'Kanni',
    order: 6,
    stars: ['Uthiram', 'Hastham', 'Chithirai'],
  },
  libra: {
    english: 'Libra',
    tanglish: 'Thulaam',
    order: 7,
    stars: ['Chithirai', 'Swati', 'Visakam'],
  },
  scorpio: {
    english: 'Scorpio',
    tanglish: 'Viruchigam',
    order: 8,
    stars: ['Visakam', 'Anusham', 'Kettai'],
  },
  sagittarius: {
    english: 'Sagittarius',
    tanglish: 'Dhanusu',
    order: 9,
    stars: ['Moolam', 'Pooradam', 'Uthiradam'],
  },
  capricorn: {
    english: 'Capricorn',
    tanglish: 'Makaram',
    order: 10,
    stars: ['Uthiradam', 'Thiruvonam', 'Avittam'],
  },
  aquarius: {
    english: 'Aquarius',
    tanglish: 'Kumbam',
    order: 11,
    stars: ['Avittam', 'Sadhayam', 'Poorattadhi'],
  },
  pisces: {
    english: 'Pisces',
    tanglish: 'Meenam',
    order: 12,
    stars: ['Poorattadhi', 'Uthirattadhi', 'Revathi'],
  },
} as const;

export const PROFILE_STATUS = {
  NEW: 'New',
  REJECTED: 'Rejected',
  CONTACTED: 'Contacted',
  MEETING_SCHEDULED: 'Meeting Scheduled',
  ACCEPTED: 'Accepted',
  ON_HOLD: 'OnHold',
  PROFILE_SHARED: 'Profile Shared',
  NEED_TO_CONTACT: 'Need to Contact',
  SHARE_BY_RM: 'Share by RM',
} as const;

export const PROFILE_STATUS_COLORS_MAP = {
  NEW: 'bg-sky-100! text-sky-700!',
  REJECTED: 'bg-rose-100! text-rose-700!',
  CONTACTED: 'bg-indigo-100! text-indigo-700!',
  MEETING_SCHEDULED: 'bg-lime-100! text-lime-700!',
  ACCEPTED: 'bg-emerald-100! text-emerald-700!',
  ON_HOLD: 'bg-amber-100! text-amber-700!',
  PROFILE_SHARED: 'bg-fuchsia-100! text-fuchsia-700!',
  SHARE_BY_RM: 'bg-orange-100! text-orange-700!',
  NEED_TO_CONTACT: 'bg-slate-200! text-slate-700!',
} as const;

export const PROFILE_STATUS_COLORS = {
  NEW: 'bg-sky-100 text-sky-700',
  REJECTED: 'bg-rose-100 text-rose-700',
  CONTACTED: 'bg-indigo-100 text-indigo-700',
  MEETING_SCHEDULED: 'bg-lime-100 text-lime-700',
  ACCEPTED: 'bg-emerald-100 text-emerald-700',
  ON_HOLD: 'bg-amber-100 text-amber-700',
  PROFILE_SHARED: 'bg-fuchsia-100 text-fuchsia-700',
  SHARE_BY_RM: 'bg-orange-100 text-orange-700',
  NEED_TO_CONTACT: 'bg-slate-200 text-slate-700',
} as const;
